# Generated by Django 4.0.5 on 2022-06-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeroone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='last_click',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='ind',
            field=models.IntegerField(default=0),
        ),
    ]
