# Generated by Django 4.0.5 on 2022-06-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeroone', '0002_counter_last_click_alter_counter_ind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='id_user',
        ),
        migrations.AddField(
            model_name='counter',
            name='ip_user',
            field=models.TextField(default='127.0.0.1'),
        ),
    ]
